# -*- coding: utf-8 -*-
"""Assignment_03_Abdul_Rehman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwtA0nRWbLRGMzazMDz4v5MJTGoBBVKr

# Assignment 03 - OpenAI and Hugging Face

**Student Name:** Abdul Rehman  
**Course:** Generative AI & Natural Language Processing  
**Date:** April 2026

---

## Assignment Overview
This notebook explores the practical application of Large Language Models (LLMs) through two primary ecosystems: **OpenAI** and **Hugging Face**. The tasks range from theoretical understanding of model architectures to building functional applications for sentiment analysis, Named Entity Recognition (NER), and content generation.
"""

import json
import os
from google.colab import _message

def fix_notebook_metadata():
    # Request the current notebook JSON
    nb_json = _message.blocking_request('get_ipynb', request='', timeout_sec=30)
    if not nb_json:
        print('Could not retrieve notebook data.')
        return

    # Clean the top-level metadata
    metadata = nb_json.get('metadata', {})
    if 'widgets' in metadata:
        del metadata['widgets']
        print('Removed global widget metadata.')

    # Strip outputs and cell-level metadata to ensure a clean push
    for cell in nb_json.get('cells', []):
        if 'outputs' in cell:
            cell['outputs'] = []
        if 'metadata' in cell:
            cell['metadata'] = {}

    file_path = 'Assignment_03_Fixed.ipynb'
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(nb_json, f, ensure_ascii=False, indent=1)

    print(f'Done! A completely stripped version has been saved as: {file_path}')
    print('This version has no outputs or widget data, which should resolve GitHub errors.')

fix_notebook_metadata()

!pip install -q openai transformers torch accelerate

import os
import getpass
from openai import OpenAI
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import torch

print("Libraries imported successfully.")

"""## Safe API Setup

In this section, we securely handle the OpenAI API key.

**Security Note:** It is critical never to hardcode API keys directly into source code. When using version control systems like GitHub, hardcoded keys can be scraped by malicious actors. Instead, we use `getpass` to input the key into the environment variables during the session only.
"""

os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter your OpenAI API Key: ")

client = None
try:
    if os.environ["OPENAI_API_KEY"]:
        client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
        print("OpenAI Client initialized successfully.")
    else:
        print("No API key detected. Please provide a key to run OpenAI-dependent cells.")
except Exception as e:
    print(f"Initialization failed: {e}")

"""## Question 1: Context Windows in LLMs

### What is a Context Window?
The context window is the maximum amount of text (measured in tokens) that a language model can "read" or consider at any one time before generating a response. Think of it as the model's short-term memory during a single conversation or task.

### Why is it typically limited?
Context windows are limited primarily due to computational costs. Most modern LLMs use the Transformer architecture, where the memory and processing power required grow quadratically with the length of the input. Processing extremely long sequences requires massive amounts of GPU RAM.

### OpenAI Model Families & Large Context
The **GPT-4** family (specifically `gpt-4-turbo` and `gpt-4o`) is known for significantly larger context windows (up to 128k tokens). This matters because it allows users to upload entire books, long legal documents, or massive codebases for analysis without the model "forgetting" the beginning of the text.

## Question 2: Challenges, Embeddings, and Fine-Tuning

### Challenges in Deployment
1. **Hallucination:** Models generating confident but false information.
2. **Bias:** Models reflecting societal prejudices found in training data.
3. **Inference Cost:** Running large models is expensive and energy-intensive.

### Addressing Challenges
Researchers use **RLHF (Reinforcement Learning from Human Feedback)** to align models with human values and **RAG (Retrieval-Augmented Generation)** to reduce hallucinations by providing the model with factual reference data.

### Understanding Embeddings
Embeddings are numerical representations of text (vectors). They convert words or sentences into a list of numbers where mathematically "close" vectors represent semantically similar meanings. This allows computers to understand relationships between concepts.

### Understanding Fine-Tuning
Fine-tuning is the process of taking a pre-trained model and training it further on a smaller, specific dataset. This adapts a general-purpose model for specialized tasks, such as medical diagnosis or specific brand voice mimicry.
"""

def analyze_sentiment(text):
    if not client:
        return "Error: OpenAI Client not configured."

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a sentiment analysis assistant. Classify the user text as Positive, Negative, or Neutral. Respond with only one word."},
                {"role": "user", "content": text}
            ]
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"API Error: {e}"

# Testing
test_samples = [
    "I absolutely love the new design of this app!",
    "The food was okay, but the service was quite slow.",
    "I am so frustrated with this constant crashing."
]

print("--- Sentiment Analysis Results ---")
for sample in test_samples:
    print(f"Text: {sample}\nSentiment: {analyze_sentiment(sample)}\n")

def calculate_similarity(text1, text2):
    if not text1 or not text2:
        return "Error: Inputs cannot be empty."
    if not client:
        return "Error: OpenAI Client not configured."

    try:
        prompt = f"Compare the following two texts and provide a similarity score from 0 to 100, where 100 means identical meaning and 0 means completely unrelated. Provide only the number.\n\nText 1: {text1}\nText 2: {text2}"
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}]
        )
        score = response.choices[0].message.content.strip()
        return f"Similarity Score: {score}/100"
    except Exception as e:
        return f"Failed to calculate similarity: {e}"

t1 = "The weather is sunny today."
t2 = "It is a bright and clear day outside."
print(calculate_similarity(t1, t2))

def generate_blog_package(topic):
    if not client: return "API Key missing."

    try:
        prompt = f"""Generate a blog post package for the topic: '{topic}'.
        Include:
        1. Title
        2. 300-word Body
        3. Keywords
        4. SEO Meta Title
        5. SEO Meta Description
        6. A descriptive prompt for an AI image generator representing this blog.
        Format each section clearly."""

        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"An error occurred: {e}"

user_topic = input("Enter a blog topic: ")
if user_topic:
    print("\n--- Generated Blog Content ---\n")
    print(generate_blog_package(user_topic))
else:
    print("No topic provided.")

"""## Question 6: Understanding Hugging Face

### What is Hugging Face?
Hugging Face is often called the "GitHub of AI." It is a massive community and platform that hosts open-source models, datasets, and demo apps (Spaces), making AI accessible to everyone.

### Why is it important?
It democratizes AI by allowing developers to use state-of-the-art models (like BERT, Llama, or Stable Diffusion) without needing the massive resources required to train them from scratch.

### Transformers and Pipelines
- **Transformers:** The specific neural network architecture that handles sequential data (like text) efficiently using 'Attention' mechanisms.
- **Pipelines:** A high-level helper function in the Hugging Face library that abstracts away complex code, allowing you to perform tasks like sentiment analysis or translation in just two lines of code.

### Hugging Face API
While many use the library locally, the **Inference API** allows you to run models hosted on Hugging Face servers via HTTP requests, similar to how we use OpenAI.
"""

def hf_sentiment_analysis(text_list):
    # Using a default pre-trained model for sentiment
    classifier = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")
    results = classifier(text_list)

    for text, res in zip(text_list, results):
        print(f"Text: {text}")
        print(f"Label: {res['label']}, Score: {res['score']:.4f}\n")

samples = [
    "This assignment is very informative!",
    "I am struggling with the complex math involved.",
    "The sun rises in the east."
]

hf_sentiment_analysis(samples)

# Updated to use 'aggregation_strategy' instead of the deprecated 'grouped_entities'
ner_pipeline = pipeline("ner", aggregation_strategy="simple")

corpus = """Apple Inc. is looking at buying a startup in San Francisco.
Meanwhile, Microsoft expanded its headquarters in Redmond, Washington last year."""

results = ner_pipeline(corpus)

print("--- Named Entity Extraction ---")
print("Companies Found:")
for ent in results:
    # Using 'entity_group' which is populated when aggregation_strategy is used
    if ent['entity_group'] == 'ORG':
        print(f"- {ent['word']}")

print("\nLocations Found:")
for ent in results:
    if ent['entity_group'] == 'LOC':
        print(f"- {ent['word']}")

generator = pipeline('text-generation', model='gpt2')

def creative_continuation(prompt, max_len=50):
    output = generator(prompt, max_length=max_len, num_return_sequences=1, truncation=True)
    return output[0]['generated_text']

prompts = [
    "In a galaxy far away, there lived a",
    "The secret to learning AI quickly is",
    "When the robot finally woke up, it said"
]

for p in prompts:
    print(f"Prompt: {p}")
    print(f"Result: {creative_continuation(p)}\n" + "-"*30)

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
sentence = "Tokenization is the first step in NLP."

inputs = tokenizer(sentence)
tokens = tokenizer.tokenize(sentence)

print(f"Original: {sentence}")
print(f"Tokens: {tokens}")
print(f"Token IDs: {inputs['input_ids']}")
print(f"Attention Mask: {inputs['attention_mask']}")

"""## What I Practiced in OpenAI and Hugging Face
- **API Integration:** Learned how to safely manage and call cloud-based models.
- **Prompt Engineering:** Experimented with system and user roles to get specific output formats.
- **Pipeline Abstraction:** Used Hugging Face pipelines to quickly deploy NER and Sentiment models.
- **Tokenization Mechanics:** Visualized how text is broken down for machine consumption.

## Challenges Faced and Notes for Future Improvement
- **Rate Limiting:** Managing API usage to avoid hitting trial limits.
- **Model Selection:** Understanding that smaller models (like GPT2) are faster but less coherent than larger ones (GPT-3.5).
- **Entity Grouping:** Realizing that NER models often split names (like 'Apple Inc.') into multiple tokens unless properly grouped.
"""
